"""empty message

Revision ID: 9d3c91ebd43a
Revises: 93e9426582ff
Create Date: 2020-10-05 22:01:43.493712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3c91ebd43a'
down_revision = '93e9426582ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('venue_id', sa.Integer(), nullable=False),
        sa.Column('artist_id', sa.Integer(), nullable=False),
        sa.Column('venue_name', sa.String(), nullable=False),
        sa.Column('artist_name', sa.String(), nullable=False),
        sa.Column('venue_image_link', sa.String(length=500), nullable=True),
        sa.Column('artist_image_link', sa.String(length=500), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
        sa.ForeignKeyConstraint(['artist_image_link'], ['Artist.image_link'], ),
        sa.ForeignKeyConstraint(['artist_name'], ['Artist.name'], ),
        sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
        sa.ForeignKeyConstraint(['venue_image_link'], ['Venue.image_link'], ),
        sa.ForeignKeyConstraint(['venue_name'], ['Venue.name'], ),
        sa.UniqueConstraint('artist_name'),
        sa.UniqueConstraint('venue_name'),
        sa.UniqueConstraint('venue_image_link'),
        sa.UniqueConstraint('artist_image_link'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
